### ISSUE TITLE
ray-2.2.0 doesn't take loggers as argument

### ISSUE THREAD

**Issue by rysio90** [piojanu/RLlogging#1]
The instruction is saying to use up-to-date installations of the underlying libraries, but with ray-2.2.0 I am getting an error that tune doesen't take loggers as argument, instead callbacks. Just replacing loggers with callbacks doesn't work.

Could you post a requirements.txt in order to know which versions were used in these examples?

**Comment by piojanu** [comment]
Hi!

Sadly, I didn't keep that venv. However, it was two years ago, so the ray version should be ~1.1.

Best,
Piotr
